name: Sync CHANGELOG

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  schedule:
    - cron: '0 0 * * *'  # Trigger daily at midnight UTC

jobs:
  sync-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Clone the source repository
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${TOKEN}@github.com/Isra3l/MolSanitizer.git
        cd MolSanitizer
        git fetch --all

    - name: Copy CHANGELOG.md
      run: |
        cp MolSanitizer/CHANGELOG.md ./

    - name: Commit and push to the documentation repository
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git clone https://x-access-token:${TOKEN}@github.com/phonglam3103/msani-readthedocs
        cp CHANGELOG.md msani-readthedocs/docs
        cd msani-readthedocs
        git add docs/CHANGELOG.md
        git commit -m "Update CHANGELOG.md from the software repository"
        git push origin main
