name: Sync CHANGELOG and Convert to RST

on:
  push:
    branches:
      - '**'  # Trigger on all branch pushes
  schedule:
    - cron: '0 0 * * *'  # Trigger daily at midnight UTC

jobs:
  sync-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Clone the source repository
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${TOKEN}@github.com/Isra3l/MolSanitizer.git
        cd MolSanitizer
        git fetch --all

    - name: Clone the documentation repository
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${TOKEN}@github.com/phonglam3103/msani-readthedocs.git

    - name: Install Pandoc for Conversion
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Compare CHANGELOG.md and Convert to RST
      run: |
        # Check if the file exists in the documentation repo
        if [ ! -f msani-readthedocs/docs/CHANGELOG.md ]; then
          echo "CHANGELOG.md not found in documentation repository. Treating as a change."
          proceed_with_conversion=true
        else
          # Compare CHANGELOG.md files
          diff_output=$(diff MolSanitizer/CHANGELOG.md msani-readthedocs/docs/CHANGELOG.md || true)
          if [ -n "$diff_output" ]; then
            echo "Detected changes in CHANGELOG.md. Proceeding with RST conversion."
            proceed_with_conversion=true
          else
            echo "No changes detected in CHANGELOG.md. Skipping RST conversion and commit."
            proceed_with_conversion=false
          fi
        fi

        # Convert to RST and commit if changes are detected or file is missing
        if [ "$proceed_with_conversion" = true ]; then
          # Convert to RST
          pandoc MolSanitizer/CHANGELOG.md -o changes.rst
          # Copy the converted RST file
          cp changes.rst msani-readthedocs/docs/source/
          cd msani-readthedocs
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Commit changes only if there are differences in changes.rst
          if ! git diff --quiet docs/source/changes.rst; then
            git add docs/source/changes.rst
            git commit -m "Update changes.rst from the software repository"
            git push origin main
          else
            echo "No changes detected in changes.rst. Skipping commit."
          fi
        fi
