name: Sync CHANGELOG and Convert to RST

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * *'  # Trigger daily at midnight UTC

jobs:
  sync-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Clone the source repository
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git clone https://x-access-token:${TOKEN}@github.com/Isra3l/MolSanitizer.git
        cd MolSanitizer
        git fetch --all

    - name: Install Pandoc for Conversion
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Copy and Convert CHANGELOG.md
      run: |
        cp MolSanitizer/CHANGELOG.md ./CHANGELOG.md
        if ! git diff --quiet CHANGELOG.md; then
          # Convert to RST
          pandoc CHANGELOG.md -o changes.rst
          # Clone the documentation repository
          git clone https://x-access-token:${TOKEN}@github.com/phonglam3103/msani-readthedocs
          # Copy the converted RST file
          cp changes.rst msani-readthedocs/docs/source/
          cd msani-readthedocs
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Commit changes only if there are differences
          if ! git diff --quiet docs/source/changes.rst; then
            git add docs/source/changes.rst
            git commit -m "Update changes.rst from the software repository"
            git push origin main
          else
            echo "No changes detected in changes.rst. Skipping commit."
          fi
        else
          echo "No changes detected in CHANGELOG.md. Skipping RST conversion and commit."
        fi
